# Generated by Django 5.2.14 on 2026-06-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.PositiveIntegerField(default=50, help_text='長表每頁顯示幾多 row（通過履歷 / details 等 server 分頁）')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
    ]
