# Generated by Django 5.2.14 on 2026-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='heli_cluster_cooldown_min',
            field=models.PositiveIntegerField(default=30, help_text='同一 cluster 幾多分鐘內唔再 push（dedup，防 spam）'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heli_cluster_enabled',
            field=models.BooleanField(default=True, help_text='開唔開直升機群集 alert（地圖橫額 + push）'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heli_cluster_min',
            field=models.PositiveIntegerField(default=4, help_text='最少幾架直升機喺範圍內先當 cluster'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='heli_cluster_radius_km',
            field=models.PositiveIntegerField(default=8, help_text='聚集判定半徑（km）'),
        ),
    ]
