# Generated by Django 5.2.14 on 2026-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftRegistryCache',
            fields=[
                ('icao', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('registration', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('lookup_source', models.CharField(blank=True, max_length=64, null=True)),
                ('last_lookup_at', models.CharField(max_length=40)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_country', models.CharField(blank=True, max_length=64, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=16, null=True)),
                ('fr24_id', models.CharField(blank=True, max_length=64, null=True)),
                ('from_airport', models.CharField(blank=True, max_length=64, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=64, null=True)),
                ('hke_notified_at', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': '機體資料',
                'verbose_name_plural': '機體資料',
                'db_table': 'aircraft_registry_cache',
            },
        ),
    ]
