# Generated by Django 5.2.14 on 2026-06-12 14:17
#
# 呢兩個欄位舊 stdlib path（src/browser_bulk_backfill.py 嘅 runtime ALTER guard、
# src/init_db.py）都會建，所以 DB 層要 idempotent：欄位已存在就 no-op，
# 唔好俾 guard 行先嘅 DB 撞 Duplicate column。Django state 層照 AddField。

from django.db import migrations, models


def _existing_columns(schema_editor):
    with schema_editor.connection.cursor() as cur:
        cur.execute(
            "SELECT COLUMN_NAME FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'aircraft_registry_cache'"
        )
        return {row[0] for row in cur.fetchall()}


def add_columns_if_missing(apps, schema_editor):
    cols = _existing_columns(schema_editor)
    with schema_editor.connection.cursor() as cur:
        if 'hke_push_failed_at' not in cols:
            cur.execute("ALTER TABLE aircraft_registry_cache ADD COLUMN hke_push_failed_at VARCHAR(40) NULL")
        if 'hke_push_fail_count' not in cols:
            cur.execute("ALTER TABLE aircraft_registry_cache ADD COLUMN hke_push_fail_count INT NOT NULL DEFAULT 0")


# Reverse 故意 no-op：啲欄位可能係 runtime guard / init_db.py 建嘅，
# 入面已經有重試 state，rollback 唔應該 drop 自己冇建過嘅嘢。
# 留低欄位無害——forward 係 idempotent，re-apply 會正確 no-op。


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_columns_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='aircraftregistrycache',
                    name='hke_push_fail_count',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='aircraftregistrycache',
                    name='hke_push_failed_at',
                    field=models.CharField(blank=True, max_length=40, null=True),
                ),
            ],
        ),
    ]
