# Generated by Django 5.2.14 on 2026-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_date', models.CharField(db_index=True, max_length=16)),
                ('icao', models.CharField(db_index=True, max_length=16)),
                ('flight', models.CharField(blank=True, max_length=32, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('category', models.CharField(blank=True, max_length=16, null=True)),
                ('first_seen', models.CharField(max_length=40)),
                ('last_seen', models.CharField(max_length=40)),
                ('samples', models.IntegerField()),
                ('min_alt_baro', models.FloatField(blank=True, null=True)),
                ('max_alt_baro', models.FloatField(blank=True, null=True)),
                ('min_gs', models.FloatField(blank=True, null=True)),
                ('max_gs', models.FloatField(blank=True, null=True)),
                ('from_airport', models.CharField(blank=True, max_length=64, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'aircraft_passes',
                'indexes': [models.Index(fields=['icao', 'pass_date'], name='idx_passes_icao_date')],
            },
        ),
        migrations.CreateModel(
            name='RouteSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('icao', models.CharField(max_length=16)),
                ('flight', models.CharField(max_length=32)),
                ('from_airport', models.CharField(blank=True, max_length=64, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=64, null=True)),
                ('observed_at', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'aircraft_route_snapshots',
                'indexes': [models.Index(fields=['icao', 'flight', 'observed_at'], name='idx_snap_icao_flight')],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.CharField(db_index=True, max_length=40)),
                ('receiver_name', models.CharField(max_length=128)),
                ('source_name', models.CharField(max_length=128)),
                ('icao', models.CharField(db_index=True, max_length=16)),
                ('flight', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(blank=True, max_length=16, null=True)),
                ('alt_baro', models.FloatField(blank=True, null=True)),
                ('alt_geom', models.FloatField(blank=True, null=True)),
                ('gs', models.FloatField(blank=True, null=True)),
                ('track', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('raw_json', models.TextField()),
            ],
            options={
                'db_table': 'sightings_raw',
                'indexes': [models.Index(fields=['icao', 'seen_at'], name='idx_sightings_icao_seen_at')],
            },
        ),
    ]
