# Generated by Django 5.2.14 on 2026-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['last_seen'], name='idx_passes_last_seen'),
        ),
    ]
