# Generated by Django 5.2.14 on 2026-06-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushrule_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushrule',
            name='callsign_prefixes',
            field=models.CharField(help_text='逗號分隔嘅 match 值，例如 callsign 用 HKE,UO；type 用 A380；icao 用 hex', max_length=128),
        ),
        migrations.AlterField(
            model_name='pushrule',
            name='label',
            field=models.CharField(help_text='顯示名，會用喺 push message 開頭', max_length=64),
        ),
    ]
