"""Legacy STRINGS dict — 由 src/web_app.py line 39-524 copy 過嚟。

過渡期：全套 i18n strings 留呢度，view 由 PlaneHistoryBaseMixin 注入畀 base.html
inline JS 嘅 `const T = ...`。Task #22 換 Django gettext / .po 之後可以剝走整個 file。
"""


LANGS = ('jp', 'hk', 'en')
DEFAULT_LANG = 'jp'
HTML_LANG_ATTR = {'jp': 'ja', 'hk': 'zh-HK', 'en': 'en'}

STRINGS = {
    'jp': {
        'site_title': '航空レーダー · plane-history',
        'details_title': '詳細 · plane-history',
        'login_title': 'ログイン · plane-history',
        'account_title': 'パスワード変更 · plane-history',
        'nav_details': '詳細',
        'nav_stats': '統計',
        'nav_home': '← トップ',
        'nav_login': 'ログイン',
        'nav_logout': 'ログアウト',
        'nav_account': 'アカウント',
        'nav_push': 'プッシュ',
        'nav_dash': 'システム',
        'dash_hdr': 'システムダッシュボード',
        'dash_uptime': 'web 稼働',
        'dash_jobs': 'LAUNCHD ジョブ',
        'dash_running': '稼働中',
        'dash_idle': '待機',
        'dash_not_loaded': '未ロード',
        'dash_health': 'フィード / DB',
        'dash_last_update': '最終サンプル経過',
        'dash_records_today': '本日のパス',
        'dash_raw_rows': 'raw 行数',
        'dash_passes': '総パス数',
        'dash_last_sample': '最終サンプル時刻',
        'dash_logs': '最近のエラー',
        'dash_log_missing': 'なし',
        'dash_log_clean': '// クリーン',
        'nav_log': 'ログ',
        'nav_watch': 'ウォッチ',
        'page_prev': '前へ',
        'page_next': '次へ',
        'page_of': '{p} / {n}',
        'watchlist_hdr': 'ウォッチリスト',
        'watchlist_intro': 'ウォッチ中の機体。機体ページで ⭐ を押すと追加。',
        'watchlist_col_last': '最終確認',
        'watchlist_unwatch': '解除',
        'watchlist_empty': '// ウォッチ中の機体なし',
        'pushlog_hdr': 'プッシュ記録',
        'pushlog_intro': '最近送ったプッシュ通知（新しい順）。',
        'pushlog_col_time': '時刻',
        'pushlog_col_label': 'ルール',
        'pushlog_col_callsign': 'コールサイン',
        'pushlog_col_reg': '登録',
        'pushlog_col_route': 'ルート',
        'pushlog_col_status': '結果',
        'pushlog_empty': '// まだプッシュなし',
        'push_hdr': 'プッシュ通知ルール',
        'push_intro': 'どの航空会社のフライトでプッシュ通知を送るか設定します。コールサインの接頭辞が一致したら通知（1機1日1回）。',
        'push_col_on': 'ON',
        'push_col_op': '航空会社',
        'push_col_prefix': 'コールサイン接頭辞',
        'push_col_type': 'タイプ',
        'push_col_val': '値',
        'ac_watch': 'ウォッチ',
        'ac_watching': 'ウォッチ中',
        'push_save': '保存',
        'push_delete': '削除',
        'push_empty': '// ルールなし',
        'push_sys_hdr': 'システム通知',
        'push_heli_label': 'ヘリ集結（事故の可能性）',
        'push_heli_desc': '近くにヘリが複数集まると通知。しきい値（機数 / 範囲 / クールダウン）は管理画面で調整。',
        'push_add_hdr': 'ルールを追加',
        'push_ph_label': '航空会社名',
        'push_add_btn': '追加',
        'stats_title': '統計 · plane-history',
        'stats_hdr_7d_hist': '直近7日 · 便数推移',
        'stats_hdr_24h_hist': '直近24時間 · 時間帯別便数 (JST)',
        'stats_hdr_7d_types': '直近7日 · 機種 TOP 10',
        'stats_hdr_7d_ops': '直近7日 · 運航会社 TOP 10',
        'stats_hdr_7d_from': '直近7日 · 出発空港 TOP 10',
        'stats_hdr_7d_to': '直近7日 · 到着空港 TOP 10',
        'stats_hdr_op_country': '直近7日 · 運航国籍 TOP 10',
        'stats_hdr_category': '直近7日 · 機種別 TOP 10',
        'stats_hdr_routes': '直近7日 · 人気ルート TOP 10',
        'stats_col_route': 'ルート',
        'stats_hdr_7d_icao': '直近7日 · 機体 TOP 10',
        'stats_hdr_db_icao': '全DB · 機体 TOP 10',
        'stats_hdr_db_total': '全DB · 累計便数',
        'stats_hdr_db_types': '全DB · 機種数',
        'stats_hdr_peak_alt': '全DB · 最高高度',
        'stats_hdr_busiest_hour': '全DB · 繁忙時間帯 (JST)',
        'stats_col_aircraft': '便数',
        'stats_col_rank': '順位',
        'nav_about': '概要',
        'about_title': 'About · plane-history',
        'about_hdr_receiver': '受信機ステータス',
        'about_hdr_project': 'このプロジェクト',
        'about_hdr_arch': 'アーキテクチャ',
        'about_lbl_receiver': '受信機',
        'about_lbl_source': 'ソース',
        'about_lbl_uptime': '稼働時間',
        'about_lbl_last_update': '最終受信',
        'about_lbl_feed': 'フィード状態',
        'about_feed_ok': 'OK · 正常',
        'about_feed_stale': '遅延',
        'about_feed_down': '停止',
        'about_ago_fmt': '{n}{u}前',
        'about_unit_sec': '秒',
        'about_unit_min': '分',
        'about_unit_hr': '時間',
        'about_unit_day': '日',
        'about_desc': '自宅に設置したADS-B受信機から航空機データを取得し、MySQLに履歴を保存。Django + DRF + gunicorn によるバックエンドAPIとWebダッシュボードで可視化、HKE便がエリアに入ったらリアルタイムでpush通知も送信します。',
        'home_subtitle': '東京・尾久の自宅受信機で取得した航空機データを記録・可視化する個人開発プロジェクトです。',
        'stats_note': 'これらの統計は MySQL に保存された過去の航空機コンタクトから算出しています。',
        'details_note': '運航会社・機種・航路・国・高度レンジで過去の航空機コンタクトを検索・絞り込みできます。',
        'about_hdr_stack': '技術スタック',
        'about_hdr_health': 'システムヘルス',
        'about_stack_frontend': 'フロントエンド',
        'about_stack_backend': 'バックエンド',
        'about_stack_db': 'データベース',
        'about_stack_receiver': '受信機',
        'about_stack_deploy': 'デプロイ',
        'about_stack_notify': '通知',
        'about_lbl_api': 'API',
        'about_lbl_db': 'データベース',
        'about_lbl_records_today': '本日の記録数',
        'nav_map': 'マップ',
        'map_title': 'ライブマップ · plane-history',
        'map_hdr': 'ライブマップ · 受信中',
        'map_unit': '機',
        'map_note': '受信機が今この瞬間に捉えている航空機を、速度と進路から滑らかに移動表示しています（tar1090 ライブ）。',
        'map_empty': '// 測位情報のある航空機が今ありません',
        'map_loading': '読み込み中...',
        'map_alt': '高度',
        'map_spd': '速度',
        'map_reg': 'レジ',
        'map_type': '機種',
        'map_op': '運航会社',
        'map_country': '国籍',
        'map_route': '区間',
        'map_vs': '昇降率',
        'map_hdg': '進路',
        'map_fr24': 'FR24 で見る',
        'map_search': '便名 / レジ で検索',
        'map_cat_all': '全機種',
        'map_cat_plane': '飛行機',
        'map_cat_heli': 'ヘリ',
        'map_cat_light': '小型',
        'map_cat_heavy': '大型',
        'map_alt_all': '全高度',
        'map_emerg_hdr': '緊急機',
        'map_clear': 'クリア',
        'map_low': '低',
        'map_high': '高',
        'map_emerg': '緊急',
        'map_heli_cluster': '⚠ {n} 機のヘリが集結 — 事故の可能性',
        'ac_title': '機体履歴 · plane-history',
        'ac_total_passes': '通過回数',
        'ac_days': '出現日数',
        'ac_first_seen': '初観測',
        'ac_last_seen': '最終観測',
        'ac_peak_alt': '最高高度',
        'ac_max_spd': '最高速度',
        'ac_daily_hdr': '直近 · 日別出現',
        'ac_passes_hdr': '通過履歴',
        'ac_col_date': '日付',
        'ac_col_time': '時刻 (JST)',
        'ac_col_flight': '便',
        'ac_col_from': '出発',
        'ac_col_to': '到着',
        'ac_col_alt': '高度',
        'ac_col_spd': '速度',
        'ac_col_samples': 'samples',
        'ac_src': 'データ元',
        'ac_updated': '更新',
        'ac_notfound': '// この ICAO の記録がありません',
        'loading': '読み込み中...',
        'no_data': '// 本日データなし',
        'cta_details': '▸  詳細ビューを開く  ▸',
        'lead_template': '{day} JST · {total}機 · {ops}社',
        'aircraft_unit': 'AIRCRAFT',
        'lbl_date': '日付',
        'lbl_sort': 'ソート',
        'lbl_country': '国',
        'lbl_operator': '運航会社',
        'lbl_type': '機種',
        'lbl_from': '出発',
        'lbl_to': '到着',
        'lbl_all': 'すべて',
        'btn_update': '更新',
        'meta_template': 'Day: {day} | Aircraft: {count} | Sort: {sort}',
        'login_heading': 'ログイン',
        'lbl_username': 'ユーザー名',
        'lbl_password': 'パスワード',
        'btn_login': 'ログイン',
        'err_login': 'ユーザー名またはパスワードが違います',
        'link_back_home': '← トップに戻る',
        'account_heading': 'パスワード変更',
        'lbl_current_pw': '現在のパスワード',
        'lbl_new_pw': '新しいパスワード',
        'lbl_confirm_pw': 'もう一度入力',
        'btn_update_pw': 'パスワードを更新',
        'err_current_wrong': '現在のパスワードが違います',
        'err_pw_mismatch': '新しいパスワードが一致しません',
        'err_pw_short': 'パスワードは6文字以上必要です',
        'ok_pw_updated': '✓ パスワードを更新しました',
        'search_placeholder': '/ で検索',
        'stats_hdr_heatmap': '直近30日 · 曜日×時間帯ヒートマップ (JST)',
        'stats_heatmap_wd': ['月','火','水','木','金','土','日'],
        'stats_heatmap_low': '少',
        'stats_heatmap_high': '多',
        'discover_hdr_curve': '累計ユニーク ICAO',
        'discover_hdr_rare': 'レアな機体 (1–2回のみ)',
        'discover_hdr_alt': '全DB · 最高高度の分布',
        'discover_hdr_top_icao': '全DB · 機体 TOP 10',
        'discover_col_first_seen': '初観測',
        'discover_col_last_seen': '最終観測',
        'discover_col_reg': 'レジ',
        'discover_col_type': '機種',
        'discover_col_op': '運航会社',
        'discover_col_passes': '回',
        'discover_curve_total_lbl': 'ユニーク ICAO',
        'discover_alt_unit': 'ft',
        'discover_no_rare': '// 該当する機体がありません',
        'ac_profile_hdr': '速度・高度プロファイル',
        'ac_profile_pick': 'pass を選択',
        'ac_profile_alt_lbl': '高度 (ft)',
        'ac_profile_gs_lbl': '速度 (kt)',
        'ac_profile_no_data': '// このpassのトラックデータがありません',
        'ac_map_hdr': 'ルートマップ',
        'ac_routes_hdr': 'ルート履歴',
        'ac_routes_empty': '// ルート記録なし',
        'ac_pruned': '// この pass の位置/軌跡 raw は保存期間（retention）を過ぎて削除済み',
        'ac_no_photo': '写真なし',
        'ac_photo_hdr': '写真',
        'ac_category': '区分',
        'ac_op_country': '運航者国籍',
        'ac_samples': '総サンプル',
        'ac_map_no_data': '// このpassの位置データがありません',
        'home_show_all': '▼ 残り {n} 機を表示',
        'cal_weekdays': '日,月,火,水,木,金,土',
        'cal_today': '今日',
        'cal_date_lbl': '日付',
        'cal_aria_choose': '日付を選択',
        'cal_aria_prev': '前の月',
        'cal_aria_next': '次の月',
    },
    'hk': {
        'site_title': '航空雷達 · plane-history',
        'details_title': '詳細 · plane-history',
        'login_title': '登入 · plane-history',
        'account_title': '改密碼 · plane-history',
        'nav_details': '詳細',
        'nav_stats': '統計',
        'nav_home': '← 首頁',
        'nav_login': '登入',
        'nav_logout': '登出',
        'nav_account': '改密碼',
        'nav_push': '推送',
        'nav_dash': '系統',
        'dash_hdr': '系統儀表板',
        'dash_uptime': 'web 運行',
        'dash_jobs': 'LAUNCHD 工作',
        'dash_running': '運行中',
        'dash_idle': '待機',
        'dash_not_loaded': '未載入',
        'dash_health': 'FEED / DB',
        'dash_last_update': '最近一筆',
        'dash_records_today': '今日 passes',
        'dash_raw_rows': 'raw 行數',
        'dash_passes': '總 passes',
        'dash_last_sample': '最近 sample',
        'dash_logs': '最近錯誤',
        'dash_log_missing': '冇',
        'dash_log_clean': '// 乾淨',
        'nav_log': '記錄',
        'nav_watch': '追蹤',
        'page_prev': '上一頁',
        'page_next': '下一頁',
        'page_of': '第 {p} / {n} 頁',
        'watchlist_hdr': '追蹤清單',
        'watchlist_intro': '你 watch 緊嘅飛機。入機頁撳 ⭐ 加入。',
        'watchlist_col_last': '最近見到',
        'watchlist_unwatch': '取消追蹤',
        'watchlist_empty': '// 未追蹤任何飛機',
        'pushlog_hdr': 'Push 記錄',
        'pushlog_intro': '最近送出嘅 push（最新喺上）。',
        'pushlog_col_time': '時間',
        'pushlog_col_label': '規則',
        'pushlog_col_callsign': 'CALLSIGN',
        'pushlog_col_reg': 'REG',
        'pushlog_col_route': '路線',
        'pushlog_col_status': '結果',
        'pushlog_empty': '// 仲未有 push',
        'push_hdr': '推送通知規則',
        'push_intro': '揀邊間航空公司嘅航班會 push 通知。callsign 前綴中咗就 push（每架機每日一次）。',
        'push_col_on': '開',
        'push_col_op': '航空公司',
        'push_col_prefix': 'CALLSIGN 前綴',
        'push_col_type': '類型',
        'push_col_val': '值',
        'ac_watch': '追蹤',
        'ac_watching': '追蹤中',
        'push_save': '儲存',
        'push_delete': '刪除',
        'push_empty': '// 未有規則',
        'push_sys_hdr': '系統提示',
        'push_heli_label': '直升機群集（疑似事故）',
        'push_heli_desc': '附近多架直升機聚集就 push（架數 / 範圍 / 冷卻時間喺 admin 調）。',
        'push_add_hdr': '加規則',
        'push_ph_label': '航空公司名',
        'push_add_btn': '加',
        'stats_title': '統計 · plane-history',
        'stats_hdr_7d_hist': '近 7 日 · 每日班次',
        'stats_hdr_24h_hist': '近 24 小時 · 每小時班次 (JST)',
        'stats_hdr_7d_types': '近 7 日 · 機型 TOP 10',
        'stats_hdr_7d_ops': '近 7 日 · 航空公司 TOP 10',
        'stats_hdr_7d_from': '近 7 日 · 出發地 TOP 10',
        'stats_hdr_7d_to': '近 7 日 · 目的地 TOP 10',
        'stats_hdr_op_country': '近 7 日 · 航空公司國籍 TOP 10',
        'stats_hdr_category': '近 7 日 · 機種類 TOP 10',
        'stats_hdr_routes': '近 7 日 · 熱門航線 TOP 10',
        'stats_col_route': '航線',
        'stats_hdr_7d_icao': '近 7 日 · 機體 TOP 10',
        'stats_hdr_db_icao': '全 DB · 機體 TOP 10',
        'stats_hdr_db_total': '全 DB · 累計班次',
        'stats_hdr_db_types': '全 DB · 機型總數',
        'stats_hdr_peak_alt': '全 DB · 最高高度',
        'stats_hdr_busiest_hour': '全 DB · 最繁忙時段 (JST)',
        'stats_col_aircraft': '班次',
        'stats_col_rank': '排名',
        'nav_about': '關於',
        'about_title': '關於 · plane-history',
        'about_hdr_receiver': '接收機狀態',
        'about_hdr_project': '關於呢個 project',
        'about_hdr_arch': '系統架構',
        'about_lbl_receiver': '接收機',
        'about_lbl_source': '來源',
        'about_lbl_uptime': '運行時間',
        'about_lbl_last_update': '最後收到',
        'about_lbl_feed': 'Feed 狀態',
        'about_feed_ok': 'OK · 正常',
        'about_feed_stale': '延遲',
        'about_feed_down': '停咗',
        'about_ago_fmt': '{n} {u}前',
        'about_unit_sec': '秒',
        'about_unit_min': '分',
        'about_unit_hr': '小時',
        'about_unit_day': '日',
        'about_desc': '呢個 project 由自宅 host 嘅 ADS-B 接收機收集飛機數據，歷史接觸記錄存入 MySQL，再透過 Django + DRF + gunicorn 後端 API 同 Web dashboard 視覺化；HKE 航班入區會即時 push 通知。',
        'home_subtitle': '由東京尾久自宅接收機收集飛機數據、記錄同視覺化嘅個人 project。',
        'stats_note': '呢啲統計係由 MySQL 入面儲存嘅歷史飛機接觸記錄計出嚟。',
        'details_note': '可以按航空公司、機型、航線、國家同高度範圍搜尋同篩選歷史飛機接觸記錄。',
        'about_hdr_stack': '技術 Stack',
        'about_hdr_health': '系統健康',
        'about_stack_frontend': '前端',
        'about_stack_backend': '後端',
        'about_stack_db': '資料庫',
        'about_stack_receiver': '接收機',
        'about_stack_deploy': '部署',
        'about_stack_notify': '通知',
        'about_lbl_api': 'API',
        'about_lbl_db': '資料庫',
        'about_lbl_records_today': '今日記錄數',
        'nav_map': '地圖',
        'map_title': '即時地圖 · plane-history',
        'map_hdr': '即時地圖 · 接收中',
        'map_unit': '架',
        'map_note': '顯示接收機而家即時捉到嘅飛機，按速度同航向平滑移動（tar1090 live）。',
        'map_empty': '// 而家冇有定位嘅飛機',
        'map_loading': '載入中...',
        'map_alt': '高度',
        'map_spd': '速度',
        'map_reg': '機牌',
        'map_type': '機型',
        'map_op': '航空公司',
        'map_country': '註冊國',
        'map_route': '航線',
        'map_vs': '升降率',
        'map_hdg': '航向',
        'map_fr24': 'FR24 詳情',
        'map_search': '搜尋 航班 / 機牌',
        'map_cat_all': '全部機型',
        'map_cat_plane': '飛機',
        'map_cat_heli': '直升機',
        'map_cat_light': '輕型',
        'map_cat_heavy': '重型',
        'map_alt_all': '全部高度',
        'map_emerg_hdr': '緊急機',
        'map_clear': '清除',
        'map_low': '低',
        'map_high': '高',
        'map_emerg': '緊急',
        'map_heli_cluster': '⚠ {n} 架直升機聚集 — 可能有事故',
        'ac_title': '機歷 · plane-history',
        'ac_total_passes': '經過次數',
        'ac_days': '出現日數',
        'ac_first_seen': '首次見到',
        'ac_last_seen': '最後見到',
        'ac_peak_alt': '最高高度',
        'ac_max_spd': '最高速度',
        'ac_daily_hdr': '近期 · 每日出現',
        'ac_passes_hdr': '經過記錄',
        'ac_col_date': '日期',
        'ac_col_time': '時間 (JST)',
        'ac_col_flight': '航班',
        'ac_col_from': '出發',
        'ac_col_to': '目的',
        'ac_col_alt': '高度',
        'ac_col_spd': '速度',
        'ac_col_samples': 'samples',
        'ac_src': '資料來源',
        'ac_updated': '更新',
        'ac_notfound': '// 冇呢個 ICAO 嘅記錄',
        'loading': '載入中...',
        'no_data': '// 今日未有資料',
        'cta_details': '▸  開詳細表  ▸',
        'lead_template': '{day} JST · {total} 架機 · {ops} 個營運商',
        'aircraft_unit': 'AIRCRAFT',
        'lbl_date': '日期',
        'lbl_sort': '排序',
        'lbl_country': '國家',
        'lbl_operator': '營運商',
        'lbl_type': '機型',
        'lbl_from': '由',
        'lbl_to': '去',
        'lbl_all': '全部',
        'btn_update': '更新',
        'meta_template': 'Day: {day} | Aircraft: {count} | Sort: {sort}',
        'login_heading': '登入 plane-history',
        'lbl_username': 'Username',
        'lbl_password': '密碼',
        'btn_login': '登入',
        'err_login': 'Username 或密碼錯誤',
        'link_back_home': '← 返首頁',
        'account_heading': '改密碼',
        'lbl_current_pw': '而家嘅密碼',
        'lbl_new_pw': '新密碼',
        'lbl_confirm_pw': '再入一次',
        'btn_update_pw': '更新密碼',
        'err_current_wrong': '而家嘅密碼錯',
        'err_pw_mismatch': '兩次新密碼唔一樣',
        'err_pw_short': '新密碼至少 6 個字',
        'ok_pw_updated': '✓ 密碼已更新',
        'search_placeholder': '/ 搜尋',
        'stats_hdr_heatmap': '近 30 日 · 星期 × 鐘數熱圖 (JST)',
        'stats_heatmap_wd': ['一','二','三','四','五','六','日'],
        'stats_heatmap_low': '少',
        'stats_heatmap_high': '多',
        'discover_hdr_curve': '累計 unique ICAO',
        'discover_hdr_rare': '罕見機 (得 1–2 次)',
        'discover_hdr_alt': '全 DB · 最高高度分佈',
        'discover_hdr_top_icao': '全 DB · 機體 TOP 10',
        'discover_col_first_seen': '首見',
        'discover_col_last_seen': '最後一次',
        'discover_col_reg': '註冊號',
        'discover_col_type': '機型',
        'discover_col_op': '航空公司',
        'discover_col_passes': '次',
        'discover_curve_total_lbl': 'unique ICAO',
        'discover_alt_unit': 'ft',
        'discover_no_rare': '// 冇符合條件嘅機',
        'ac_profile_hdr': '速度 · 高度 profile',
        'ac_profile_pick': '揀 pass',
        'ac_profile_alt_lbl': '高度 (ft)',
        'ac_profile_gs_lbl': '速度 (kt)',
        'ac_profile_no_data': '// 呢個 pass 冇 track 點',
        'ac_map_hdr': '路線地圖',
        'ac_routes_hdr': '路線歷史',
        'ac_routes_empty': '// 冇路線記錄',
        'ac_pruned': '// 呢個 pass 嘅位置/軌跡 raw 已過保留期（retention）清走',
        'ac_no_photo': '冇相',
        'ac_photo_hdr': '相片',
        'ac_category': '類別',
        'ac_op_country': '航空公司國籍',
        'ac_samples': '總取樣',
        'ac_map_no_data': '// 呢個 pass 冇位置點',
        'home_show_all': '▼ 仲有 {n} 架 · 撳開晒',
        'cal_weekdays': '日,一,二,三,四,五,六',
        'cal_today': '今日',
        'cal_date_lbl': '日期',
        'cal_aria_choose': '揀日期',
        'cal_aria_prev': '上個月',
        'cal_aria_next': '下個月',
    },
    'en': {
        'site_title': 'Aviation Radar · plane-history',
        'details_title': 'Details · plane-history',
        'login_title': 'Sign in · plane-history',
        'account_title': 'Change password · plane-history',
        'nav_details': 'DETAILS',
        'nav_stats': 'STATS',
        'nav_home': '← HOME',
        'nav_login': 'SIGN IN',
        'nav_logout': 'SIGN OUT',
        'nav_account': 'ACCOUNT',
        'nav_push': 'PUSH',
        'nav_dash': 'DASH',
        'dash_hdr': 'SYSTEM DASHBOARD',
        'dash_uptime': 'web uptime',
        'dash_jobs': 'LAUNCHD JOBS',
        'dash_running': 'RUNNING',
        'dash_idle': 'IDLE',
        'dash_not_loaded': 'NOT LOADED',
        'dash_health': 'FEED / DB',
        'dash_last_update': 'last sample ago',
        'dash_records_today': 'passes today',
        'dash_raw_rows': 'raw rows',
        'dash_passes': 'total passes',
        'dash_last_sample': 'last sample',
        'dash_logs': 'RECENT ERRORS',
        'dash_log_missing': 'missing',
        'dash_log_clean': '// clean',
        'nav_log': 'LOG',
        'nav_watch': 'WATCH',
        'page_prev': 'PREV',
        'page_next': 'NEXT',
        'page_of': '{p} / {n}',
        'watchlist_hdr': 'WATCHLIST',
        'watchlist_intro': 'Aircraft you watch — open one and tap ⭐ to add.',
        'watchlist_col_last': 'LAST SEEN',
        'watchlist_unwatch': 'Unwatch',
        'watchlist_empty': '// not watching any aircraft',
        'pushlog_hdr': 'PUSH LOG',
        'pushlog_intro': 'Recent push notifications (latest first).',
        'pushlog_col_time': 'TIME',
        'pushlog_col_label': 'RULE',
        'pushlog_col_callsign': 'CALLSIGN',
        'pushlog_col_reg': 'REG',
        'pushlog_col_route': 'ROUTE',
        'pushlog_col_status': 'STATUS',
        'pushlog_empty': '// no pushes yet',
        'push_hdr': 'PUSH RULES',
        'push_intro': 'Choose which operators trigger a push. A push fires when a callsign prefix matches (once per aircraft per day).',
        'push_col_on': 'ON',
        'push_col_op': 'OPERATOR',
        'push_col_prefix': 'CALLSIGN PREFIX',
        'push_col_type': 'TYPE',
        'push_col_val': 'VALUE',
        'ac_watch': 'WATCH',
        'ac_watching': 'WATCHING',
        'push_save': 'Save',
        'push_delete': 'Delete',
        'push_empty': '// no rules',
        'push_sys_hdr': 'SYSTEM ALERTS',
        'push_heli_label': 'Helicopter cluster (possible incident)',
        'push_heli_desc': 'Push when several helicopters cluster nearby. Thresholds (count / radius / cooldown) in admin.',
        'push_add_hdr': 'Add operator rule',
        'push_ph_label': 'operator name',
        'push_add_btn': 'Add',
        'stats_title': 'Stats · plane-history',
        'stats_hdr_7d_hist': '7-DAY · DAILY FLIGHTS',
        'stats_hdr_24h_hist': 'LAST 24H · FLIGHTS BY HOUR (JST)',
        'stats_hdr_7d_types': '7-DAY · TOP 10 TYPES',
        'stats_hdr_7d_ops': '7-DAY · TOP 10 OPERATORS',
        'stats_hdr_7d_from': '7-DAY · TOP 10 FROM',
        'stats_hdr_7d_to': '7-DAY · TOP 10 TO',
        'stats_hdr_op_country': '7-DAY · TOP 10 OPERATOR COUNTRY',
        'stats_hdr_category': '7-DAY · TOP 10 CATEGORY',
        'stats_hdr_routes': '7-DAY · TOP 10 ROUTES',
        'stats_col_route': 'ROUTE',
        'stats_hdr_7d_icao': '7-DAY · TOP 10 AIRCRAFT',
        'stats_hdr_db_icao': 'ALL-TIME · TOP 10 AIRCRAFT',
        'stats_hdr_db_total': 'ALL-TIME · TOTAL FLIGHTS',
        'stats_hdr_db_types': 'ALL-TIME · TOTAL TYPES',
        'stats_hdr_peak_alt': 'ALL-TIME · PEAK ALT',
        'stats_hdr_busiest_hour': 'ALL-TIME · BUSIEST HOUR (JST)',
        'stats_col_aircraft': 'FLIGHTS',
        'stats_col_rank': '#',
        'nav_about': 'ABOUT',
        'about_title': 'About · plane-history',
        'about_hdr_receiver': 'RECEIVER STATUS',
        'about_hdr_project': 'ABOUT THIS PROJECT',
        'about_hdr_arch': 'ARCHITECTURE',
        'about_lbl_receiver': 'Receiver',
        'about_lbl_source': 'Source',
        'about_lbl_uptime': 'Uptime',
        'about_lbl_last_update': 'Last aircraft update',
        'about_lbl_feed': 'Feed health',
        'about_feed_ok': 'OK',
        'about_feed_stale': 'DELAYED',
        'about_feed_down': 'DOWN',
        'about_ago_fmt': '{n} {u} ago',
        'about_unit_sec': 'sec',
        'about_unit_min': 'min',
        'about_unit_hr': 'hr',
        'about_unit_day': 'day',
        'about_desc': 'Self-hosted ADS-B receiver feeding into a Django + DRF + gunicorn backend, with MySQL for historical contacts and a real-time web dashboard. HKE flights entering the area trigger a push notification.',
        'home_subtitle': 'Personal ADS-B flight data dashboard powered by a self-hosted receiver in Oku, Tokyo.',
        'stats_note': 'These statistics are calculated from historical aircraft contacts stored in MySQL.',
        'details_note': 'Search and filter historical aircraft contacts by operator, aircraft type, route, country and altitude range.',
        'about_hdr_stack': 'TECH STACK',
        'about_hdr_health': 'SYSTEM HEALTH',
        'about_stack_frontend': 'Frontend',
        'about_stack_backend': 'Backend',
        'about_stack_db': 'Database',
        'about_stack_receiver': 'Receiver',
        'about_stack_deploy': 'Deployment',
        'about_stack_notify': 'Notification',
        'about_lbl_api': 'API',
        'about_lbl_db': 'Database',
        'about_lbl_records_today': 'Records today',
        'nav_map': 'MAP',
        'map_title': 'Live Map · plane-history',
        'map_hdr': 'LIVE MAP · NOW SCANNING',
        'map_unit': 'aircraft',
        'map_note': 'Aircraft currently picked up by the receiver, animated smoothly from speed and heading (tar1090 live).',
        'map_empty': '// no aircraft with position right now',
        'map_loading': 'loading...',
        'map_alt': 'ALT',
        'map_spd': 'SPD',
        'map_reg': 'REG',
        'map_type': 'TYPE',
        'map_op': 'OPERATOR',
        'map_country': 'COUNTRY',
        'map_route': 'ROUTE',
        'map_vs': 'V/S',
        'map_hdg': 'HDG',
        'map_fr24': 'VIEW ON FR24',
        'map_search': 'search flight / reg',
        'map_cat_all': 'ALL TYPES',
        'map_cat_plane': 'PLANES',
        'map_cat_heli': 'HELI',
        'map_cat_light': 'LIGHT',
        'map_cat_heavy': 'HEAVY',
        'map_alt_all': 'ALL ALT',
        'map_emerg_hdr': 'EMERGENCY',
        'map_clear': 'CLEAR',
        'map_low': 'LOW',
        'map_high': 'HIGH',
        'map_emerg': 'EMERGENCY',
        'map_heli_cluster': '⚠ {n} helicopters clustered — possible incident',
        'ac_title': 'Aircraft · plane-history',
        'ac_total_passes': 'Total passes',
        'ac_days': 'Days seen',
        'ac_first_seen': 'First seen',
        'ac_last_seen': 'Last seen',
        'ac_peak_alt': 'Peak altitude',
        'ac_max_spd': 'Max speed',
        'ac_daily_hdr': 'RECENT · DAILY APPEARANCES',
        'ac_passes_hdr': 'PASS HISTORY',
        'ac_col_date': 'DATE',
        'ac_col_time': 'TIME (JST)',
        'ac_col_flight': 'FLIGHT',
        'ac_col_from': 'FROM',
        'ac_col_to': 'TO',
        'ac_col_alt': 'ALT',
        'ac_col_spd': 'SPEED',
        'ac_col_samples': 'SAMPLES',
        'ac_src': 'SOURCE',
        'ac_updated': 'updated',
        'ac_notfound': '// no records for this ICAO',
        'loading': 'loading...',
        'no_data': '// no data today',
        'cta_details': '▸  OPEN DETAILED VIEW  ▸',
        'lead_template': '{day} JST · {total} aircraft · {ops} operators',
        'aircraft_unit': 'AIRCRAFT',
        'lbl_date': 'Date',
        'lbl_sort': 'Sort',
        'lbl_country': 'Country',
        'lbl_operator': 'Operator',
        'lbl_type': 'Type',
        'lbl_from': 'From',
        'lbl_to': 'To',
        'lbl_all': 'all',
        'btn_update': 'Update',
        'meta_template': 'Day: {day} | Aircraft: {count} | Sort: {sort}',
        'login_heading': 'Sign in to plane-history',
        'lbl_username': 'Username',
        'lbl_password': 'Password',
        'btn_login': 'Sign in',
        'err_login': 'Wrong username or password',
        'link_back_home': '← Back to home',
        'account_heading': 'Change password',
        'lbl_current_pw': 'Current password',
        'lbl_new_pw': 'New password',
        'lbl_confirm_pw': 'Confirm new password',
        'btn_update_pw': 'Update password',
        'err_current_wrong': 'Current password is wrong',
        'err_pw_mismatch': 'New passwords do not match',
        'err_pw_short': 'Password must be at least 6 characters',
        'ok_pw_updated': '✓ Password updated',
        'search_placeholder': '/ to search',
        'stats_hdr_heatmap': 'LAST 30D · WEEKDAY × HOUR HEATMAP (JST)',
        'stats_heatmap_wd': ['MON','TUE','WED','THU','FRI','SAT','SUN'],
        'stats_heatmap_low': 'LOW',
        'stats_heatmap_high': 'HIGH',
        'discover_hdr_curve': 'CUMULATIVE UNIQUE ICAO',
        'discover_hdr_rare': 'RARE FINDS (1–2 PASSES ONLY)',
        'discover_hdr_alt': 'ALL-DB · MAX ALT DISTRIBUTION',
        'discover_hdr_top_icao': 'ALL-DB · TOP 10 AIRCRAFT',
        'discover_col_first_seen': 'FIRST SEEN',
        'discover_col_last_seen': 'LAST SEEN',
        'discover_col_reg': 'REG',
        'discover_col_type': 'TYPE',
        'discover_col_op': 'OPERATOR',
        'discover_col_passes': 'N',
        'discover_curve_total_lbl': 'unique ICAO',
        'discover_alt_unit': 'ft',
        'discover_no_rare': '// no matches',
        'ac_profile_hdr': 'SPEED · ALTITUDE PROFILE',
        'ac_profile_pick': 'pick pass',
        'ac_profile_alt_lbl': 'ALT (ft)',
        'ac_profile_gs_lbl': 'GS (kt)',
        'ac_profile_no_data': '// no track points for this pass',
        'ac_map_hdr': 'ROUTE MAP',
        'ac_routes_hdr': 'ROUTE HISTORY',
        'ac_routes_empty': '// no route history',
        'ac_pruned': '// raw position/track pruned (past retention)',
        'ac_no_photo': 'NO PHOTO',
        'ac_photo_hdr': 'PHOTO',
        'ac_category': 'CATEGORY',
        'ac_op_country': 'OPERATOR COUNTRY',
        'ac_samples': 'SAMPLES',
        'ac_map_no_data': '// no position points for this pass',
        'home_show_all': '▼ SHOW {n} MORE AIRCRAFT',
        'cal_weekdays': 'SU,MO,TU,WE,TH,FR,SA',
        'cal_today': 'TODAY',
        'cal_date_lbl': 'DATE',
        'cal_aria_choose': 'Choose date',
        'cal_aria_prev': 'Previous month',
        'cal_aria_next': 'Next month',
    },
}
